server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

spring:
  application:
    name: user-service
  profiles:
    active: dev

  config:
    import: "configserver:http://localhost:9000"

  cloud:
    config:
      username: admin
      password: admin